# JSM Form Configuration
# For authentication with Atlassian Cloud, you need:
# - username: Your email address used for Atlassian login
# - token_atlassian_api: An API token (NOT your account password)
# - microsoft_password: Your Microsoft/Entra password used during interactive login
#
# To create an API token:
# 1. Go to https://id.atlassian.com/manage-profile/security/api-tokens
# 2. Click "Create API token"
# 3. Give it a name and copy the generated token
# 4. Use that token as the password below

# Organization name (your Atlassian subdomain)
org = "your-organization"
# Full base URL (should match your org name)
base_url = "https://your-organization.atlassian.net"
# Portal and request type IDs (find these in your JSM instance)
portal_id = 6
request_type_id = 73

[auth]
# Your Atlassian account email address
username = "your-email@domain.com"
# Your Atlassian API token (create at the URL above)
token_atlassian_api = "your-api-token-here"
# Your Microsoft/Entra password used when the browser automation logs in
microsoft_password = "your-microsoft-password"