# Example TOML file for JSM ticket creation
# This file contains the field data for creating a Normal Change request

# Required fields
summary = "TEST Pieter - Deploy new application version 2.3.1"

# Required datetime fields (use ISO 8601 format with timezone)
# Format: YYYY-MM-DDTHH:MM:SS.sss+ZZZZ
customfield_10878 = "2025-09-23T14:00:00.000+1300"  # Planned start
customfield_10879 = "2025-09-23T16:00:00.000+1300"  # Planned end

# Optional fields
description = "This change deploys version 2.3.1 of the customer portal application including bug fixes and performance improvements."

# Optional change management fields
customfield_10883 = """Implementation plan:
1. Stop application services at 14:00
2. Deploy new version from staging
3. Update configuration files
4. Restart services
5. Run smoke tests
6. Monitor for 30 minutes"""

customfield_10884 = """Backout plan:
1. Stop application services
2. Restore previous version from backup
3. Restore previous configuration
4. Restart services
5. Verify functionality"""

customfield_10885 = """Test plan:
1. Verify application starts successfully
2. Test user login functionality
3. Test key user workflows
4. Check performance metrics
5. Verify database connectivity"""

customfield_11024 = "This deployment fixes critical security vulnerabilities and performance issues identified in production."

customfield_11025 = """Impact analysis:
- Low risk deployment during maintenance window
- No database changes required
- Minimal user impact (30 minute downtime)
- All tests passed in staging environment"""

# Risk Assessment Configuration (for use with risk-assessment command)
[risk_assessment]

[risk_assessment.change_impact_assessment]
# Security Impact - only configuring the first field as requested
security_controls_impact = "No"  # Options: Yes/No/I don't know

# Affected services (using exact format from web interface)
[[customfield_10243]]
id = "ari:cloud:graph::service/9ff4cfc8-0856-11eb-a1a9-0a77f3f45304/b60f4bd2-68d1-11ef-952e-1201f16ed41f"
name = "Azure Cloud"
description = ""

[customfield_10243.tier]
level = 1